---
hero_image: images/wanted.png
theme: oranje
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: maker, ontwerp-0, programmeren-0, phys-comp-0, productie-0, community-0
title: Gezocht!
description: Leer hoe je je eigen poster kunt maken.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: 'kunst en ontwerp'
technologies: html/css
site_areas: codeclub, webdev
steps:
  - 
    title: Inleiding
  - 
    title: Je poster stylen
  - 
    title: 'Uitdaging: je poster verbeteren'
  - 
    title: Afbeeldingen opmaken
  - 
    title: 'Uitdaging: je afbeelding verbeteren'
  - 
    title: Koppen opmaken
  - 
    title: 'Uitdaging: maak je poster geweldig!'
  - 
    title: 'Uitdaging: adverteer een evenement!'

