---
hero_image: images/wanted.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Wanted!
description: Learn how to make your own poster.
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.0.1
last_tested: 2024-11-28
steps:
- title: What you will make
- title: Styling your poster
  completion:
  - engaged
- title: Styling images
- title: Styling headings
  completion:
  - internal
- title: 'Challenge'
  challenge: true
- title: What can you do now?
