---
hero_image: images/wanted.png
theme: नारंगी
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Wanted!
description: Learn how to make your own poster.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: art and design
technologies: html/css
site_areas: प्रोजेक्ट
hardware: ''
software: htmp-css-javascript
version: 3.0.1
last_tested: 2017-01-01
steps:
  - 
    title: भूमिका
  - 
    title: Styling your poster
  - 
    title: 'Challenge: Improving your poster'
  - 
    title: Styling images
  - 
    title: 'Challenge: Improving your image'
  - 
    title: Styling headings
  - 
    title: 'Challenge: Make your poster awesome!'
  - 
    title: 'Challenge: Advertise an event!'
