---
hero_image: छवियों / जरूरत.png
theme: नारंगी
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: रचनाकार, डिजाइन -1, प्रोग्रामिंग -0, फिजिकल-कम्प -0, निर्माण -0, समुदाय -0
title: जरूरत!
description: अपना स्वयं का पोस्टर बनाना सीखें।
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: कला और डिजाइन
technologies: html-css-javascript
site_areas: codeclub, webdev
hardware: ''
software: htmp-css-javascript
version: 3.0.1
last_tested: 2017-01-01
steps:
  - 
    title: परिचय
  - 
    title: अपने पोस्टर को स्टाइल करते हुए
  - 
    title: 'चुनौती: आपके पोस्टर में सुधार करना'
  - 
    title: चित्रों को स्टाइल देना
  - 
    title: 'चुनौती: आपके चित्र में सुधार करना'
  - 
    title: स्टाइलिंग हेडिंग
  - 
    title: 'चुनौती: आपके पोस्टर को अद्भुत बनाना!'
  - 
    title: 'चुनौती: एक इवेंट का प्रचार करें!'
