---
hero_image: images/wanted.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Procurado!
description: Aprende a fazer o teu próprio cartaz.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.0.1
last_tested: 2017-01-01
steps:
  - title: Introdução
  - title: Estilizar o teu cartaz
  - title: 'Desafio: Melhorar o teu cartaz'
  - title: Estilizar imagens
  - title: 'Desafio: Melhorar a tua imagem'
  - title: Estilizar cabeçalhos
  - title: 'Desafio: Torna o teu poster fantástico!'
  - title: 'Desafio: Anuncia um evento!'
