---
hero_image: images/wanted.png
theme: naranča
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tražen!
description: Saznajte kako izraditi vlastiti poster.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: art
technologies: html-css-javascript
site_areas: projekti
hardware: ''
software: html-css-javascript
version: 3.0.1
last_tested: 2017-01-01
steps:
  - 
    title: Sretan rođendan
  - 
    title: Oblikovanje vašeg postera
  - 
    title: 'Izazov: Poboljšajte svoj poster'
  - 
    title: Uređivanje slike
  - 
    title: 'Izazov: Poboljšajte svoju sliku'
  - 
    title: Naslovi za oblikovanje
  - 
    title: 'Izazov: Učinite vaš poster još boljim!'
  - 
    title: 'Izazov: Oglašavajte događaj!'
