---
hero_image: images/wanted.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Procurado!
description: Learn how to make your own poster.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: arte
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.0.1
last_tested: 01/01/2017
steps:
  - 
    title: Introdução
  - 
    title: Estilizando seu pôster
  - 
    title: 'Desafio: Melhorar seu poster'
  - 
    title: Dando estilo a imagens
  - 
    title: 'Desafio: melhorar sua imagem'
  - 
    title: Estilizando Cabeçalhos
  - 
    title: 'Desafio: Torne seu pôster incrível!'
  - 
    title: 'Desafio: Anuncie um evento!'
