---
hero_image: images / wanted.png
theme: Jeruk
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, desain-1, pemrograman-0, phys-comp-0, manufacture-0, community-0
title: Ingin!
description: Pelajari cara membuat poster Anda sendiri.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: seni
technologies: html-css-javascript
site_areas: proyek
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: pengantar
  - 
    title: Pasang poster Anda
  - 
    title: 'Tantangan: Memperbaiki poster Anda'
  - 
    title: Gambar Styling
  - 
    title: 'Tantangan: Meningkatkan citra Anda'
  - 
    title: Judul gaya
  - 
    title: 'Tantangan: Buat poster Anda luar biasa!'
  - 
    title: 'Tantangan: Iklankan acara!'
