---
hero_image: images / wanted.png
theme: narancs
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Wanted!
description: Tudja meg, hogyan készítheti el saját plakátját.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.0.1
last_tested: 2017-01-01
steps:
  - 
    title: Bevezetés
  - 
    title: A poszter stílusa
  - 
    title: 'Kihívás: A poszter fejlesztése'
  - 
    title: Stílusos képek
  - 
    title: 'Kihívás: A kép javítása'
  - 
    title: Stílus fejlécek
  - 
    title: 'Kihívás: tedd félelmetesvé a posztert!'
  - 
    title: 'Kihívás: Hirdessen egy eseményt!'
