---
hero_image: images/wanted.png
theme: برتقالة
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: مطلوب!
description: تعلم كيف تصنع الملصق الخاص بك.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: فن
technologies: html-css-javascript
site_areas: codeclub, python
hardware: ''
software: html-css-javascript
version: 3.0.1
last_tested: 2017-01-01
steps:
  - 
    title: المقدمة
  - 
    title: تحديد أنماط الملصق
  - 
    title: 'التحدي: حسِّن شكل الملصق!'
  - 
    title: تحديد أنماط الصور
  - 
    title: 'التحدي: حسِّن شكل الصورة!'
  - 
    title: تحديد أنماط العناوين
  - 
    title: 'التحدي: اجعل ملصقك يبدو مثيرًا للاهتمام!'
  - 
    title: 'التحدي: أَعلِن عن حدث!'
