---
hero_image: images/wanted.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tagaotsitav!
description: Vaadake, kuidas oma posterit koostada.
original_url: https://codeclubprojects.org/en-GB/webdev/ soovitud
interests: art
technologies: html-css-javascript
site_areas: projektid
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Sissejuhatus
  - 
    title: Plakati kujundamine
  - 
    title: 'Väljakutse: parandage oma plakat'
  - 
    title: Piltide kujundamine
  - 
    title: 'Väljakutse: pildi parandamine'
  - 
    title: Stiilirubad
  - 
    title: 'Väljakutse: tehke oma plakat suurepäraseks!'
  - 
    title: 'Väljakutse: reklaamige üritust!'
