---
hero_image: images/wanted.png
theme: pomarańczowy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Wanted!
description: Naucz się, jak stworzyć własny plakat.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: sztuka
technologies: html-css-javascript
site_areas: projekty
hardware: ''
software: HTML, css i javascript
version: 3
last_tested: 1. I. 2017
steps:
  - 
    title: Wprowadzenie
  - 
    title: Stylizowanie swojego plakatu
  - 
    title: 'Wyzwanie: poprawienie swojego plakatu'
  - 
    title: Stylizacja obrazów
  - 
    title: 'Challenge: Improving your image'
  - 
    title: Stylizacja nagłówków
  - 
    title: 'Challenge: Make your poster awesome!'
  - 
    title: 'Wyzwanie: Reklamuj wydarzenie!'
