---
hero_image: images/wanted.png
theme: pomarańczowy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Poszukiwany!
description: Naucz się, jak stworzyć własny plakat.
original_url: https://codeclubprojects.org/pl-PL/webdev/wanted
interests: sztuka
technologies: HTML, css i javascript
site_areas: projekty
hardware: ''
software: HTML, css i javascript
version: 3
last_tested: 1. I. 2017
steps:
  - 
    title: Wprowadzenie
  - 
    title: Stylizowanie swojego plakatu
  - 
    title: 'Wyzwanie: poprawienie swojego plakatu'
  - 
    title: Stylizacja obrazów
  - 
    title: 'Wyzwanie: poprawa obrazu'
  - 
    title: Stylizacja nagłówków
  - 
    title: 'Wyzwanie: Spraw, by Twój plakat był niesamowity!'
  - 
    title: 'Wyzwanie: Reklamuj wydarzenie!'
