---
hero_image: images/wanted.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tražen!
description: Nauči kako da napraviš sopstveni plakat.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
  completion: engaged
- title: Stilizovanje plakata
- title: 'Izazov: Poboljšaj svoj plakat'
- title: Stilizovanje slika
- title: 'Izazov: Poboljšaj svoju sliku'
- title: Stilizovanje naslova
- title: 'Izazov: Napravi fenomenalan plakat!'
  completion: internal
- title: 'Izazov: Reklamiraj događaj!'
