---
hero_image: images/wanted.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Ricercato!
description: Impara a creare il tuo poster.
original_url: https://codeclubprojects.org/it-IT/webdev/wanted/
interests: art
technologies: html-css-javascript
site_areas: progetti
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Disegnare il tuo poster
  - 
    title: 'Sfida: Migliora il tuo poster'
  - 
    title: Modificare l'aspetto delle immagini
  - 
    title: 'Sfida: Migliora la tua immagine'
  - 
    title: Personalizzare le intestazioni
  - 
    title: 'Sfida: rendi fantastico il tuo poster!'
  - 
    title: 'Sfida: pubblicizza un evento!'
