---
hero_image: images/wanted.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Ricercato!
description: Impara a creare il tuo poster.
original_url: https://codeclubprojects.org/it-IT/webdev/wanted/
interests: art
technologies: html-css-javascript
site_areas: progetti
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Dai stile al tuo poster
  - 
    title: 'Sfida: Migliorare il tuo poster'
  - 
    title: Dai stile alle tue immagini
  - 
    title: 'Sfida: Migliorare la tua immagine'
  - 
    title: Dare stile all'intestazione
  - 
    title: 'Sfida: Rendi bellissimo il tuo poster!'
  - 
    title: 'Sfida: Pubblicizza un evento!'
