---
hero_image: images/wanted.png
theme: turuncu
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-1, programlama-0, phys-comp-0, üretim-0, topluluk-0
title: Aranıyor!
description: Kendi posterinizi nasıl yapacağınızı öğrenin.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: sanat
technologies: html CSS-JavaScript
site_areas: projeler
hardware: ''
software: html CSS-JavaScript
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Giriş
  - 
    title: Posterinizi şekillendirin
  - 
    title: 'Meydan Okuma: Posterinizi geliştirme'
  - 
    title: Görüntüleri şekillendirme
  - 
    title: 'Meydan Okuma: Resminizi iyileştirme'
  - 
    title: Başlıkları biçimlendirme
  - 
    title: 'Meydan okuma: Posterini mükemmelleştir!'
  - 
    title: 'Meydan Okuma: Bir etkinliğin reklamını yap!'
