---
hero_image: images/wanted.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Aranıyor!
description: Kendi posterinizi nasıl yapacağınızı öğrenin.
original_url: https://codeclubprojects.org/en-GB/webdev/wanted
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.0.1
last_tested: 01/01/2017
steps:
- title: Giriş
- title: Posterinizi şekillendirin
- title: 'Meydan Okuma: Posterinizi geliştirme'
- title: Görüntüleri şekillendirme
  completion:
  - engaged
- title: 'Meydan Okuma: Resminizi iyileştirme'
- title: Başlıkları şekillendirme
  completion:
  - internal
- title: 'Meydan Okuma: Posterini mükemmelleştir!'